# Generated by Django 5.2.1 on 2025-06-05 08:44

import modules.xQuire.models
import modules.xQuire.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_xQuire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='extracted_assets',
            field=models.JSONField(blank=True, help_text='List of files extracted from archive', null=True),
        ),
        migrations.AlterField(
            model_name='firmware',
            name='file',
            field=models.FileField(storage=modules.xQuire.storage.FirmwareStorage(), upload_to=modules.xQuire.models.firmware_file_path),
        ),
    ]
