# Generated by Django 5.2.1 on 2025-08-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_xScout', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
