# Generated by Django 5.2.1 on 2025-09-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_xFormation', '0001_initial'),
        ('modules_xQuire', '0002_firmware_extracted_assets_alter_firmware_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the device', max_length=200)),
                ('rootfs_path', models.CharField(help_text='Path to rootfs.tar.gz', max_length=500)),
                ('penguin_project_path', models.CharField(blank=True, max_length=500, null=True)),
                ('initialization_status', models.CharField(choices=[('not_initialized', 'Not Initialized'), ('initializing', 'Initializing'), ('initialized', 'Initialized'), ('init_failed', 'Initialization Failed')], default='not_initialized', max_length=20)),
                ('initialization_log', models.TextField(blank=True, help_text='Penguin init output log', null=True)),
                ('config_yaml_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firmware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules_xQuire.firmware')),
            ],
            options={
                'verbose_name': 'Emulated Device',
                'verbose_name_plural': 'Emulated Devices',
            },
        ),
        migrations.CreateModel(
            name='EmulationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=100)),
                ('process_id', models.IntegerField(blank=True, help_text='Penguin process PID', null=True)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='starting', max_length=20)),
                ('cpu_limit', models.FloatField(default=2.0, help_text='CPU cores limit')),
                ('memory_limit', models.CharField(default='1g', help_text='Memory limit (e.g., 1g, 512m)', max_length=10)),
                ('host_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('host_ports', models.JSONField(default=dict, help_text='Port mappings from penguin')),
                ('web_interface_url', models.URLField(blank=True, null=True)),
                ('web_interface_status', models.CharField(choices=[('unknown', 'Unknown'), ('accessible', 'Accessible'), ('inaccessible', 'Inaccessible')], default='unknown', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_health_check', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('output_log_path', models.CharField(blank=True, max_length=500, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules_xFormation.emulateddevice')),
            ],
            options={
                'verbose_name': 'Emulation Instance',
                'verbose_name_plural': 'Emulation Instances',
            },
        ),
    ]
