# Generated by Django 5.2.1 on 2025-09-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_xFormation', '0002_emulateddevice_emulationinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulateddevice',
            name='has_rootfs',
            field=models.BooleanField(default=False, help_text='Whether rootfs.tar.gz exists'),
        ),
        migrations.AddField(
            model_name='emulateddevice',
            name='rootfs_discovered_at',
            field=models.DateTimeField(blank=True, help_text='When rootfs.tar.gz was first discovered', null=True),
        ),
        migrations.AlterField(
            model_name='emulateddevice',
            name='rootfs_path',
            field=models.CharField(blank=True, help_text='Path to rootfs.tar.gz', max_length=500, null=True),
        ),
    ]
