# Generated by Node Emulation Engine implementation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_xFormation', '0003_emulateddevice_has_rootfs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emulateddevice',
            name='config_data',
            field=models.JSONField(blank=True, default=dict, help_text='User configuration applied during initialization'),
        ),
    ]
