# Generated by Django 5.2.1 on 2025-11-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules_xFormation', '0004_add_docker_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emulationinstance',
            name='process_id',
            field=models.IntegerField(blank=True, help_text='Penguin process PID (for subprocess mode)', null=True),
        ),
    ]
