# Generated by Django 5.2.1 on 2026-02-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules_xFormation', '0004_add_config_data'),
        ('modules_xFormation', '0006_emulationinstance_penguin_results_path_and_more'),
    ]

    operations = [
    ]
